### PR TITLE
bring gravity binary to test_runner

### PR DESCRIPTION
**Pull request by mvid**

### CODE REVIEW

**Comment by mvid** [comment]
@levicook @jtremback can you review this if it is still needed, or close if not?

**Comment by levicook** [comment]
Closing. I don’t think we will need it.

**Comment by levicook** [comment]
Correction -- just found that this is useful for the valset stress e2e tests.

**Comment by levicook** [comment]
Since this is a single commit, I'm going to cherry-pick it and try it out.

**Comment by levicook** [comment]
Cherry picked into #43 
Fails with `error checking context: 'can't stat '/home/levi/gravity-bridge/testdata/testchain/gravity0/data/cs.wal''.`

Which I recall seeing now. Pretty sure that's a level-db write ahead log & pretty sure it's using stringent permissions on Linux I might be able to relax. Will investigate...

**Comment by levicook** [comment]
Marking as draft because #45 should make this unnecessary.

**Comment by levicook** [comment]
#45 is successfully delegating (albeit with a race condition on tx sequence numbers); closing

**Pull request closed without merging**
