### PR TITLE
One e2e scaffolding to rule them all...

### PR DESCRIPTION
**Pull request by levicook**
The goal of this PR is to establish one canonical way of running our end-2-end tests (aka integration tests) by eliminating the shell+docker-compose infrastructure with the (CI friendly) dockertest equivalents.

The root project Makefile presents the most reliable way of running all of our e2e tests in a repeatable and reliable way. There’s a make target for each e2e suite and there’s a make target to run them all serially.

To run an individual e2e test, choose one of the following targets:
- e2e_batch_stress
- e2e_happy_path
- e2e_validator_out
- e2e_valset_stress
- e2e_v2_happy_path
- e2e_arbitrary_logic
- e2e_orchestrator_keys

To run them all serially, choose:
- e2e_slow_loris

These targets methodically ensure you're running in a pristine e2e testing environment. When any of these targets fail, they invoke `make fail`; which will dump logs for all containers participating in the test into the testdata folder (maybe not the ideal place, but I wanted something we already .gitignore). 

Here's what you should expect from a test failure:

```bash
$ make e2e_slow_loris
=== RUN   TestHappyPath
    e2e_happy_path_test.go:10: building and running ethereum
    e2e_happy_path_test.go:10: deployed ethereum at 6e3bba4c1fada4cf24fafe01881057279ec6d47ad56da088f9a963a21d8ae3ad
    e2e_happy_path_test.go:10: building gravity0
    e2e_happy_path_test.go:10: building gravity1
    e2e_happy_path_test.go:10: building gravity2
    e2e_happy_path_test.go:10: building gravity3
    e2e_happy_path_test.go:10: deployed gravity0 at 7198fd735ba1ee926c1bf8e819c48bb8b27b10085c673a7b7b0c8aea0d7aa84b
    e2e_happy_path_test.go:10: deployed gravity1 at da0bb139139f9ad09a484bacc4c4bc42c2725b69b7a4115555eccd5d314eae4a
    e2e_happy_path_test.go:10: deployed gravity2 at 2c638e5e2cb99625c411a47e54cc60e2a9fce2bb257cd4c599a17fa99a4b050a
    e2e_happy_path_test.go:10: deployed gravity3 at 0d547dac818e1d5415a41f22ba9cba6aa45b046e88aefbb6bb642a2c42a08adf
    e2e_happy_path_test.go:10: building contract_deployer
    e2e_happy_path_test.go:10: deployed contract_deployer at 6adb152109cdbba2679b1337049bca124c86c1c3384834a7b3f1be0fcbb9aa8d
    e2e_happy_path_test.go:10: building orchestrator0
    e2e_happy_path_test.go:10: building orchestrator1
    e2e_happy_path_test.go:10: building orchestrator2
    e2e_happy_path_test.go:10: building orchestrator3
    e2e_happy_path_test.go:10: deployed orchestrator0 at e1c37c1f97bc41ac8ac3e4c049245526dba7cb1cf8f83da4666addc299cedf0e
    e2e_happy_path_test.go:10: deployed orchestrator1 at 0d760a80f0b795efd2a273c0666b443d48ae616222880ae363fc8fa6178bbcc5
    e2e_happy_path_test.go:10: deployed orchestrator2 at 5f874b0754ee570330b36866e92f553c75e888b9c47e844384f65d99b437792b
    e2e_happy_path_test.go:10: deployed orchestrator3 at 87e58a7d5b441ec45bcb87d333cafb0c39c33226522aa6aa0e467007415ebb92
    e2e_happy_path_test.go:15: building and deploying test runner
    e2e_happy_path_test.go:15: deployed test runner at 8d52a4750689c07514d63623d23d000bcf78569c6333f29d8eaa47d0d851aa44
--- PASS: TestHappyPath (219.33s)
PASS
=== RUN   TestV2HappyPath
    e2e_v2_happy_path_test.go:10: building and running ethereum
    e2e_v2_happy_path_test.go:10: deployed ethereum at c65ed9791d24b1b898ee2830d4e10e5fbdb5a9f00e563db66a2336846264dbb7
    e2e_v2_happy_path_test.go:10: building gravity0
    e2e_v2_happy_path_test.go:10: building gravity1
    e2e_v2_happy_path_test.go:10: building gravity2
    e2e_v2_happy_path_test.go:10: building gravity3
    e2e_v2_happy_path_test.go:10: deployed gravity0 at 7ce7d0ceddca18213fad23f64983cf540f54ee6959ab1efe62887863a290e902
    e2e_v2_happy_path_test.go:10: deployed gravity1 at df389596630079a4aeb1b0c9ffa34728fe978ca6b7165610fd93f5bfb8a2c5e8
    e2e_v2_happy_path_test.go:10: deployed gravity2 at f9d0aff89c251d471e132d748f9516f0e4f31c940db14a66a5ea782fb9eb9449
    e2e_v2_happy_path_test.go:10: deployed gravity3 at c697f8358939d0354145abc46b12e4d304c942220de4770b9848fb94ddcfcff8
    e2e_v2_happy_path_test.go:10: building contract_deployer
    e2e_v2_happy_path_test.go:10: deployed contract_deployer at ce17beafd23f92859a3bd106a1102b558016dad8ac2e15abb0c0233ef75cdb3a
    e2e_v2_happy_path_test.go:10: building orchestrator0
    e2e_v2_happy_path_test.go:10: building orchestrator1
    e2e_v2_happy_path_test.go:10: building orchestrator2
    e2e_v2_happy_path_test.go:10: building orchestrator3
    e2e_v2_happy_path_test.go:10: deployed orchestrator0 at 36b192e6a48433ff2e7b919c385c38909ce25e9929c9ba0c9994f6c3b5ad4177
    e2e_v2_happy_path_test.go:10: deployed orchestrator1 at c6054c226ef190158d6542bd44d195cbd940a4b1b12105097524bba728fd35b9
    e2e_v2_happy_path_test.go:10: deployed orchestrator2 at b19dd420f95eddea545c4dbe72abb1fa136f600d742e9fcd6b3d0c1ce24534eb
    e2e_v2_happy_path_test.go:10: deployed orchestrator3 at de75cec48d3713cd16ce5bba77078a6ffe1023e42d24067a21596ae35bbb23f4
    e2e_v2_happy_path_test.go:15: building and deploying test runner
    e2e_v2_happy_path_test.go:15: deployed test runner at 1553fe2971d1e3658c552ff8ba482ed7636abfbcbc623590067db3b2550de114
    e2e_v2_happy_path_test.go:15:
                Error Trace:    testnet_test.go:92
                                                        e2e_v2_happy_path_test.go:15
                                                        with_pristine_e2e_environment_test.go:367
                                                        e2e_v2_happy_path_test.go:10
                Error:          Not equal:
                                expected: 0
                                actual  : 101
                Test:           TestV2HappyPath
                Messages:       container exited with error
--- FAIL: TestV2HappyPath (416.48s)
FAIL
test failed; dumping container logs into ./testdata for review
make[2]: *** [Makefile:57: fail] Error 1
make[1]: *** [Makefile:47: e2e_v2_happy_path] Error 2
make: *** [Makefile:5: e2e_slow_loris] Error 2

$ ls -1 testdata/*.log
testdata/contract_deployer.log
testdata/gravity0.log
testdata/gravity1.log
testdata/gravity2.log
testdata/gravity3.log
testdata/orchestrator0.log
testdata/orchestrator1.log
testdata/orchestrator2.log
testdata/orchestrator3.log
testdata/test_runner.log

$ cat testdata/test_runner.log
[2021-07-08T19:35:20Z INFO  test_runner] Staring Gravity test-runner
[2021-07-08T19:35:20Z INFO  test_runner] COSMOS_NODE_GRPC http://192.168.32.3:9090
[2021-07-08T19:35:20Z INFO  test_runner] Waiting for Cosmos chain to come online
[2021-07-08T19:35:24Z INFO  test_runner] Starting tests with Ok("V2_HAPPY_PATH")
[2021-07-08T19:35:24Z INFO  test_runner] Starting happy path for Gravity v2
[2021-07-08T19:35:30Z INFO  test_runner::happy_path_v2] Successfully deployed new ERC20 representing FooToken on Cosmos with event nonce 2
thread 'main' panicked at 'Cosmos did not adopt the ERC20 contract for footoken it must be invalid in some way', test_runner/src/happy_path_v2.rs:89:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: test_runner::happy_path_v2::happy_path_test_v2::{{closure}}
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::macros::scoped_tls::ScopedKey<T>::set
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::macros::scoped_tls::ScopedKey<T>::set
   7: tokio::runtime::Runtime::block_on
   8: test_runner::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### CODE REVIEW

**Comment by levicook** [comment]
The local state of these tests is:

```
e2e_arbitrary_logic   -- passing
e2e_happy_path        -- passing
e2e_orchestrator_keys -- passing
e2e_v2_happy_path     -- passing

e2e_validator_out     -- failing
e2e_valset_stress     -- failing
e2e_batch_stress      -- failing
```

Interesting to see that's disjoint from CI; which is currently:

```
rust-build -- failing (?!)
validator-out -- failing
valset-stress -- failing
batch-stress -- failing
v2-happy-path -- failing
arbitrary-logic -- failing
orchestrator-keys -- failing
```

**Comment by levicook** [comment]
I'm marking this as "Ready for Review" because it does what it set out to do -- remove the shell + docker-compose e2e test-runner.

Unfortunately, our e2e tests aren't all passing under the new go test + dockertest e2e runner leaving this PR and the project in an unclear state on whether to pay attention to or ignore e2e test failures.

I don't think that PR created that condition, but maybe slightly worsens it. Would love to hear what reviewers think about this & whether they think this should be merged or not.

**Comment by jackzampolin** [comment]
I'm down to merge this and open another branch for debugging the e2e failures. Goal to get all green asap

**Comment by levicook** [comment]
It’s very nice to see “All checks have passed” here. Let’s just create issues to track the e2e tests we need to bring back to life

**Comment by levicook** [comment]
I'm merging this, then filing issues to restore / get each of the broken e2e tests back into working order. Will also file an issue to remove the `tests` folder and another to document "how to test" this project.

**Pull request merged**
