### PR TITLE
Cherry picked: Improved proto generation script

### PR DESCRIPTION
**Pull request by levicook**
This improved proto gen script comes with credit to Tony upstream on the
github.com/cosmos/cosmos-rust repo.

Cherry picked from Justin's work in the althea-net repo:
https://github.com/althea-net/cosmos-gravity-bridge/commit/cebad5a535570336b1b52f0a6ba13259c1052b95

### CODE REVIEW

**Comment by levicook** [comment]
In draft because I cherry picked and pushed, but haven't tested.

**Comment by levicook** [comment]
Seems to work well -- one issue I notice is that our generated code is sometimes run through a formatter and sometimes not, leading to noise like this:

```rust
diff --git a/orchestrator/gravity_proto/src/prost/gravity.v1.rs b/orchestrator/gravity_proto/src/prost/gravity.v1.rs
index 24db1804..f0e1396b 100644
--- a/orchestrator/gravity_proto/src/prost/gravity.v1.rs
+++ b/orchestrator/gravity_proto/src/prost/gravity.v1.rs
@@ -3,29 +3,29 @@
 /// once the required threshold is met.
 #[derive(Clone, PartialEq, ::prost::Message)]
 pub struct EthereumEventVoteRecord {
-    #[prost(message, optional, tag = "1")]
+    #[prost(message, optional, tag="1")]
     pub event: ::core::option::Option<::prost_types::Any>,
-    #[prost(string, repeated, tag = "2")]
+    #[prost(string, repeated, tag="2")]
     pub votes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
-    #[prost(bool, tag = "3")]
+    #[prost(bool, tag="3")]
     pub accepted: bool,
```

I can't tell if the code generator is or isn't formatting things. I suspect it isn't but people's editors are? Not sure.

**Comment by levicook** [comment]
I think there are unexpected issues with this update.
1. Unexpected modifications to generated files
2. Unexpected untracked file

The modifications to `gravity_proto/src/prost/gravity.v1.rs` appear to be rustfmt related. Guessing we need to either:
- teach proto_tool to rustfmt or
- teach editors not to rustfmt the generated code

I'm not sure if the new untracked file is good & useful, or noise we shouldn't commit: `gravity_proto/src/prost/cosmos_proto.rs`

```bash
$ cd  orchestrator/proto_build && cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/Users/levi/somm/gravity-bridge-1/orchestrator/target/debug/proto_build`
[info] Compiling .proto files to Rust into '../gravity_proto/src/prost/'...
[info ] Compiling proto clients for GRPC services!
Copying generated files into '../gravity_proto/src/prost/'...
[info ] => Done!

$ git status
On branch levi/improve-rust-proto-gen
Your branch is up to date with 'origin/levi/improve-rust-proto-gen'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   gravity_proto/src/prost/gravity.v1.rs

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        gravity_proto/src/prost/cosmos_proto.rs

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by levicook** [comment]
Looking into how easy or hard running rustfmt over the generated code is. If it's easy (and it probably is) I'll integrate that because it's a) easier to control than editors and b) a better code reading / code navigation experience too.

**Comment by levicook** [comment]
Note to self `--edition=2018` matters.

```bash
rustfmt --emit=files --edition=2018  gravity.v1.rs
oogi:prost levi$ git status .
On branch levi/improve-rust-proto-gen
Your branch is up to date with 'origin/levi/improve-rust-proto-gen'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cosmos_proto.rs
```

**Comment by jackzampolin** [comment]
Rust still isn't building (says CI) anything left here @levicook ?

**Comment by levicook** [comment]
Looking at the Rust build question now. Will fix and merge

**Comment by levicook** [comment]
Hmm. I'm not sure why, but the generated code contains new annotations that affect that `use` statement.

Here's what it's adding
```rust
 #[cfg(feature = "grpc")]
 #[cfg_attr(docsrs, doc(cfg(feature = "grpc")))]
```

And here's what it breaks
```rust
use gravity_proto::gravity::query_client::QueryClient as GravityQueryClient;
```

Manually commenting out those lines makes it work like it used to. Going to investigate why they're inserted now, but weren't before. Doesn't seem related to anything I did, but 🤷

**Pull request merged**
